### ISSUE TITLE
Intent to participate - CHARLES BUKOWSKI ALL CAPS

### ISSUE THREAD

**Issue by SandroMiccoli** [dariusk/NaNoGenMo-2015#139]
I'm already working on some code over Charles Bukowski's work and his usage of CAPS TO EMPHASIZE SHIT (and also the excessively usage of PROFANE LANGUAGE).

I've created small independent zines with only the words in CAPS of each of his books, but that's not even close to 50k words...

Still didn't think EXACTLY what I'm going to do but I just found out about this AND DECIDED TO POST AN INTENT TO PARTICIPATE.

CHEERS

**Comment by MichaelPaulukonis** [comment]
THAT is something that could be PRETTY F****G INTERESTING.
