### ISSUE TITLE
Intent to participate: Completely new

### ISSUE THREAD

**Issue by hnotess** [dariusk/NaNoGenMo-2015#147]
Hello, I am completely new to coding of any kind, but a NaNoGenMo project sounds like fun. I am thinking of creating some kind of N + 7 procedure on a Project Gutenberg text. For this to work, I need to find a good dictionary/list of nouns.

**Comment by ikarth** [comment]
There's a few different dictionaries around, depending on how involved you want to get and exactly what kind of shift you want to implement. Something like the public domain [Moby Parts of Speech list](http://icon.shef.ac.uk/Moby/mpos.html), while not the most recent and up-to-date project might be a good starting point if you're using the relationship of words in a dictionary, versus something like WordNet that has less concept of the alphabetized order of the words. It mostly depends on what twist you want to put on it.

**Comment by hnotess** [comment]
Hmm... not this year. Maybe by next year I'll have enough knowledge to build something for NaNoGenMo!

**Comment by MichaelPaulukonis** [comment]
See you in 11 months!
