### ISSUE TITLE
Dada Engine-like implementation in Python

### ISSUE THREAD

**Issue by tresoldi** [dariusk/NaNoGenMo-2015#195]
Hello all,

during NaNoGenMo I had started to write a Python implementation of the famous Dada Engine, but didn't manage to finish in time. It is still a bit raw (very beta, if you want the jargon), but it is working and might help you during NaNoGenMo 2016. You can get it [here](https://github.com/tresoldi/tzara), MIT license.

Feel free to fork, push and the like. :)

**Comment by enkiv2** [comment]
Nice :)

**Comment by MichaelPaulukonis** [comment]
Oh! And Javascript!
