### ISSUE TITLE
a future entry goes here

### ISSUE THREAD

**Issue by robotsnowfall** [dariusk/NaNoGenMo-2015#84]
Declaring intent.

**Comment by robotsnowfall** [comment]
Current status:

> meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow

Waiting on ETL...

**Comment by robotsnowfall** [comment]
Bah, life got in the way. Next year!

**Comment by greg-kennedy** [comment]
$ perl -e 'print "meow " x 50000'
